### ISSUE TITLE
SVG render issue

### ISSUE THREAD

**Issue by danielcobo** [sarahdayan/lamp-mvc#1]
![lamp](https://user-images.githubusercontent.com/7779810/28628508-1e866f98-7225-11e7-818b-9d5a0324a0c2.png)

There is an issue with the SVG, as you can see the shaded part is not aligned with the top of the lamp.
This screenshot is from the latest OSX Sierra, running Safari.

**Comment by sarahdayan** [comment]
Thanks for letting me know @danielcobo! The issue was fixed in [032ee6088f7a98831843f9b7d5c44fa0a6e8b0ec](https://github.com/sarahdayan/lamp-mvc/commit/032ee6088f7a98831843f9b7d5c44fa0a6e8b0ec).
